// Parsable Entries gathered from the Technical Manual
module.exports.entryDefinitions = [
  {
    transactionCode: '01',
    name: 'start',
    originalName: 'Startpost',
    properties: {
      layoutName: {
        length: 20,
        startPos: 3,
        endPos: 22,
        format: 'A:vb',
      },
      version: {
        length: 2,
        startPos: 23,
        endPos: 24,
        format: 'A:vb',
      },
      timestamp: {
        length: 20,
        startPos: 25,
        endPos: 44,
        format: 'N:-',
      },
      enviromentTag: {
        length: 1,
        startPos: 45,
        endPos: 45,
        format: 'A:-',
      },
    },
  },
  {
    transactionCode: '05',
    name: 'chapterStart',
    originalName: 'Öppningspost',
    properties: {
      recipientBankgiroNumber: {
        length: 10,
        startPos: 3,
        endPos: 12,
        format: 'N:h0',
      },
      recipientPlusgiroNumber: {
        length: 10,
        startPos: 13,
        endPos: 22,
        format: 'N:h0/A:b',
      },
      currency: {
        length: 3,
        startPos: 23,
        endPos: 25,
        format: 'A:b',
      },
    },
  },
  {
    transactionCode: '20',
    name: 'payment',
    originalName: 'Betalningspost',
    properties: {
      senderBankgiroNumber: {
        length: 10,
        startPos: 3,
        endPos: 12,
        format: 'N:h0',
      },
      reference: {
        length: 25,
        startPos: 13,
        endPos: 37,
        formatMap: { // Depends on 'referenceCode'
          0: '-:-',
          1: '-:-',
          2: 'N:hb',
          3: 'A:-',
          4: 'A:vb',
          5: 'A:-',
        },
      },
      paymentAmount: {
        length: 18,
        startPos: 38,
        endPos: 55,
        format: 'N:h0',
      },
      referenceCode: {
        length: 1,
        startPos: 56,
        endPos: 56,
        format: 'N:-',
      },
      paymentMethod: {
        length: 1,
        startPos: 57,
        endPos: 57,
        format: 'N:-',
        possibleValues: {
          1: 'Betalningen är en elektronisk betalning från bank.',
          2: 'Betalningen är en elektronisk betalning från tjänsten Leverantörsbetalningar (LB).',
          3: 'Betalningen är en blankettbetalning',
          4: 'Betalningen är en elektronisk betalning från tjänsten Autogiro (AG).',
        },
      },
      BGCSerialNumber: {
        length: 12,
        startPos: 58,
        endPos: 69,
        format: 'N:-',
      },
      aviImage: {
        length: 1,
        startPos: 70,
        endPos: 70,
        format: 'N:-',
        possibleValues: {
          0: 'Ingen avibild finns. Innebär att betalning har gjorts elektroniskt eller med OCR-avi.',
          1: 'Avibild finns. Innebär att betalning gjorts med girering-/inbetalningsavi.',
          2: 'Reserverade för framtida bruk',
        },
      },
    },
  },
  {
    transactionCode: '21',
    name: 'deduction',
    originalName: 'Avdragspost',
    properties: {
      senderBankgiroNumber: {
        length: 10,
        startPos: 3,
        endPos: 12,
        format: 'N:h0',
      },
      reference: {
        length: 25,
        startPos: 13,
        endPos: 37,
        formatMap: { // Depends on 'referenceCode'
          0: '-:-',
          1: '-:-',
          2: 'N:hb',
          3: 'A:-',
          4: 'A:vb',
          5: 'A:-',
        },
      },
      paymentAmount: {
        length: 18,
        startPos: 38,
        endPos: 55,
        format: 'N:h0',
      },
      referenceCode: {
        length: 1,
        startPos: 56,
        endPos: 56,
        format: 'N:-',
      },
      paymentMethod: {
        length: 1,
        startPos: 57,
        endPos: 57,
        format: 'N:-',
        possibleValues: {
          1: 'Betalningen är en elektronisk betalning från bank.',
          2: 'Betalningen är en elektronisk betalning från tjänsten Leverantörsbetalningar (LB).',
          3: 'Betalningen är en blankettbetalning',
          4: 'Betalningen är en elektronisk betalning från tjänsten Autogiro (AG).',
        },
      },
      BGCSerialNumber: {
        length: 12,
        startPos: 58,
        endPos: 69,
        format: 'N:-',
      },
      aviImage: {
        length: 1,
        startPos: 70,
        endPos: 70,
        format: 'N:-',
        possibleValues: {
          0: 'Ingen avibild finns. Innebär att betalning har gjorts elektroniskt eller med OCR-avi.',
          1: 'Avibild finns. Innebär att betalning gjorts med girering-/inbetalningsavi.',
          2: 'Reserverade för framtida bruk',
        },
      },
      deductionCode: {
        length: 1,
        startPos: 71,
        endPost: 71,
        format: 'N:-',
      },
    },
  },
  {
    transactionCode: ['22', '23'],
    name: 'extraReferenceNumber',
    originalName: 'Extra referensnummerpost',
    properties: {
      senderBankgiroNumber: {
        length: 10,
        startPos: 3,
        endPos: 12,
        format: 'N:h0',
      },
      reference: {
        length: 25,
        startPos: 13,
        endPos: 37,
        formatMap: { // Depends on 'referenceCode'
          0: '-:-',
          1: '-:-',
          2: 'N:hb',
          3: 'A:-',
          4: 'A:vb',
          5: 'A:-',
        },
      },
      paymentAmount: {
        length: 18,
        startPos: 38,
        endPos: 55,
        format: 'N:h0',
      },
      referenceCode: {
        length: 1,
        startPos: 56,
        endPos: 56,
        format: 'N:-',
      },
      paymentMethod: {
        length: 1,
        startPos: 57,
        endPos: 57,
        format: 'N:-',
        possibleValues: {
          1: 'Betalningen är en elektronisk betalning från bank.',
          2: 'Betalningen är en elektronisk betalning från tjänsten Leverantörsbetalningar (LB).',
          3: 'Betalningen är en blankettbetalning',
          4: 'Betalningen är en elektronisk betalning från tjänsten Autogiro (AG).',
        },
      },
      BGCSerialNumber: {
        length: 12,
        startPos: 58,
        endPos: 69,
        format: 'N:-',
      },
      aviImage: {
        length: 1,
        startPos: 70,
        endPos: 70,
        format: 'N:-',
        possibleValues: {
          0: 'Ingen avibild finns. Innebär att betalning har gjorts elektroniskt eller med OCR-avi.',
          1: 'Avibild finns. Innebär att betalning gjorts med girering-/inbetalningsavi.',
          2: 'Reserverade för framtida bruk',
        },
      },
    },
  },
  {
    transactionCode: '25',
    name: 'information',
    originalName: 'Informationspost',
    properties: {
      informationText: {
        length: 50,
        startPos: 3,
        endPos: 52,
        format: 'A:-',
      },
    },
  },
  {
    transactionCode: '26',
    name: 'name',
    originalName: 'Namnpost',
    properties: {
      payerName: {
        length: 35,
        startPos: 3,
        endPos: 37,
        format: 'A:vb',
      },
      extraNameField: {
        length: 35,
        startPos: 38,
        endPos: 72,
        format: 'A:vb',
      },
    },
  },
  {
    transactionCode: '27',
    name: 'address1',
    originalName: 'Adresspost',
    properties: {
      payerAddress: {
        length: 35,
        startPos: 3,
        endPos: 37,
        format: 'A:vb',
      },
      payerPostalCode: {
        length: 9,
        startPos: 38,
        endPos: 46,
        format: 'A:vb',
      },
    },
  },
  {
    transactionCode: '28',
    name: 'address2',
    originalName: 'Adresspost 2',
    properties: {
      payerAddress: {
        length: 35,
        startPos: 3,
        endPos: 37,
        format: 'A:vb',
      },
      payerCountry: {
        length: 35,
        startPos: 38,
        endPos: 72,
        format: 'A:vb',
      },
      payerCountryCode: {
        length: 2,
        startPos: 73,
        endPos: 74,
        format: 'A:vb',
      },
    },
  },
  {
    transactionCode: '29',
    name: 'address2',
    originalName: 'Adresspost 2',
    properties: {
      organisationNumber: {
        length: 12,
        startPos: 3,
        endPos: 14,
        format: 'N:h0',
      },
    },
  },
  {
    transactionCode: '15',
    name: 'chapterEnd',
    originalName: 'Insättningspost',
    properties: {
      recipientBankAccountNumber: {
        length: 35,
        startPos: 3,
        endPos: 37,
        format: 'N:h0',
      },
      paymentDay: {
        length: 8,
        startPos: 38,
        endPos: 45,
        format: 'N:-',
      },
      depositSerialNumber: {
        length: 5,
        startPos: 46,
        endPos: 50,
        format: 'N:h0',
      },
      depositAmount: {
        length: 18,
        startPos: 51,
        endPos: 68,
        format: 'N:h0',
      },
      currency: {
        length: 3,
        startPos: 69,
        endPos: 71,
        format: 'A:-',
      },
      paymentCount: {
        length: 8,
        startPos: 72,
        endPos: 79,
        format: 'A:-',
      },
      depositType: {
        length: 1,
        startPos: 80,
        endPost: 80,
        format: "':'",
      },
    },
  },
  {
    transactionCode: '70',
    name: 'end',
    originalName: 'Slutpost',
    properties: {
      paymentEntriesCount: {
        length: 8,
        startPos: 3,
        endPos: 10,
        format: 'N:h0',
      },
      deductionEntriesCount: {
        length: 8,
        startPos: 11,
        endPos: 18,
        format: 'N:h0',
      },
      extraReferenceEntriesCount: {
        length: 8,
        startPos: 19,
        endPos: 26,
        format: 'N:h0',
      },
      chapterEndEntriesCount: {
        length: 8,
        startPos: 27,
        endPos: 34,
        format: 'N:h0',
      },
    },
  },
];
